name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GH Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${{ secrets.GH_ACCESS_TOKEN }}
          build_configuration: production
          base_href: /azure-storage-sas-token-generator/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/sas-generator
