name: Build and Deploy
 on:
   push:
     branches:
       - master
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Deploy to GH Pages
       uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.3.1
       with:
         github_access_token: ${{ secrets.ACCESS_TOKEN }}
         build_configuration: production
         base_href: /azure-storage-sas/
         deploy_branch: gh-pages
         angular_dist_build_folder: dist/azure-storage-sas
