name: Format code
on:
  pull_request:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Format code
        run: |
          npm ci
          npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
